backend:
  name: github
  repo: tusher984/Tusher-Portfolio # আপনার গিটহাব ইউজারনেম এবং রেপোজিটরির নাম
  branch: main # আপনার মূল ব্রাঞ্চ

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "stories"
    label: "Selected Works (Stories)"
    folder: "content"
    extension: "json"
    format: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Standfirst", name: "standfirst", widget: "text"}
      - {label: "Outlet", name: "outlet", widget: "string"}
      - {label: "Format", name: "format", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean"}